
---
dependencies: []

galaxy_info:
  author: ag0n1k
  description: Nginx installation for Rhel.
  company: "Otus Linux"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.6
  platforms:
    - name: EL
      versions:
      - 7
