---
- name: Install ipa-server packages
  yum:
    name: "{{ otus_ipa_server_packages }}"
    state: present

- name: Install ipa-server
  command: >
    ipa-server-install -U \
      -r {{ otus_ipa_server_realm }} \
      -n {{ otus_ipa_server_domain }} \
      -p {{ otus_ipa_server_master_password }} \
      -a {{ otus_ipa_server_db_password }} \
      --hostname={{ otus_ipa_server_hostname }} \
      --ip-address={{ otus_ipa_server_ip }} \
      --setup-dns \
      --auto-forwarders \
      --no-reverse
  args:
    creates: /etc/ipa/default.conf