- block:
  - name: Verify Python3 import
    script: py3test.py
    failed_when: false
    changed_when: false
    register: otus_ipa_server_py3test

  - name: Set python interpreter to 3
    when: otus_ipa_server_py3test.rc == 0
    set_fact:
      ansible_python_interpreter: "/usr/bin/python3"

  - name: Fail for IPA 4.5.90
    when: otus_ipa_server_py3test.rc != 0 and "not usable with python3" in otus_ipa_server_py3test.stdout
    fail: msg="You need to install python2 bindings for ipa server usage"

  - name: Set python interpreter to 2
    when: otus_ipa_server_py3test.failed or otus_ipa_server_py3test.rc != 0
    set_fact:
      ansible_python_interpreter: "/usr/bin/python2"
