---
prometheus_archive_path: >-
  https://github.com/prometheus/prometheus/releases/download/v2.5.0/prometheus-2.5.0.darwin-amd64.tar.gz

prometheus_user_configuration:
  username: prometheus
  group: prometheus
  system: true
  shell: /sbin/nologin
  home: /usr/lib/prometheus
  ##note: in prometheus home directory will be unpacked distro,
  # unpacked logic works only when directory does not exist, but user must exist so:
  # - create user and define home, without creating home directory
  # - unpack distro and create home directory
  # also if need to install in other directory there is an opportunity to define another root_path and path
  create_home: false

prometheus_path: /usr/lib/prometheus
prometheus_path_mode: "0755"

prometheus_data_dir: /var/lib/prometheus/data
prometheus_data_dir_mode: "0750"
prometheus_data_dir_force: false

prometheus_conf_dir: /etc/prometheus
prometheus_conf_dirs_mode: "0750"

prometheus_bin_dir: /usr/bin

prometheus_no_log: true
