---
prometheus_archive_path: >-
  https://github.com/prometheus/prometheus/releases/download/v2.5.0/prometheus-2.5.0.darwin-amd64.tar.gz

prometheus_user_configuration:
  username: prometheus
  group: prometheus
  system: true
  shell: /sbin/nologin
  home: /usr/lib/prometheus
  ##note: in prometheus home directory will be unpacked distro,
  # unpacked logic works only when directory does not exist, but user must exist so:
  # - create user and define home, without creating home directory
  # - unpack distro and create home directory
  # also if need to install in other directory there is an opportunity to define another root_path and path
  create_home: false

prometheus_path: "/usr/lib/prometheus"
prometheus_path_mode: "0755"

prometheus_data_dir: "/var/lib/prometheus/data"
prometheus_data_dir_mode: "0750"
prometheus_data_dir_force: false

prometheus_conf_dir: /etc/prometheus
prometheus_conf_dirs_mode: "0750"

prometheus_bin_dir: /usr/bin

prometheus_no_log: true

nginx_worker_processes: "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
nginx_worker_connections: "1024"
nginx_multi_accept: "off"

nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"

nginx_server_tokens: "on"

nginx_client_max_body_size: "64m"

nginx_server_names_hash_bucket_size: "64"

nginx_remove_default_vhost: false

nginx_listen: 8080
nginx_server_name: anv.otuslinux.com

nginx_log_format: |
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'