# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  config.vm.define "ipaserver" do |ipaserver|
    ipaserver.vm.hostname = "ipaserver.test.local"
    ipaserver.vm.network "private_network", ip: "192.168.11.101"

    ipaserver.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = "1"
    end
  end

  config.vm.define "ipaclient" do |ipaclient|
    ipaclient.vm.hostname = "ipaclient.test.local"
    ipaclient.vm.network "private_network", ip: "192.168.11.102"

    ipaclient.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = "1"
    end
  end
end
